# Generated by Django 5.2.4 on 2025-08-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP_Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('custo_centavos', models.BigIntegerField()),
                ('peso_und', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unidade', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_revisao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
