# Generated by Django 5.2.4 on 2025-08-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mp_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterField(
            model_name='mp_produtos',
            name='data_revisao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
