# Generated by Django 5.2.4 on 2025-08-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_cliente_alter_mp_produtos_data_revisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orcamento', models.CharField(max_length=50)),
                ('revisao', models.IntegerField(default=1)),
                ('cliente', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('contato', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('instalacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('venda_destinada', models.CharField(max_length=200)),
                ('cliente_contrib_icms', models.BooleanField()),
                ('cnpj_faturamento', models.CharField(max_length=20)),
                ('icms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Ajuste', 'Ajuste'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado'), ('Convertido', 'Convertido')], default='Rascunho', max_length=15)),
                ('validade', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('desconto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('imposto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoHistorico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('versao', models.IntegerField()),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviado', 'Enviado'), ('Ajuste', 'Ajuste'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado'), ('Convertido', 'Convertido')], max_length=15)),
                ('alterado_por', models.CharField(max_length=150)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('descricao_mudanca', models.TextField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='main.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_item', models.CharField(choices=[('Produto', 'Produto'), ('Serviço', 'Serviço')], max_length=10)),
                ('descricao', models.CharField(max_length=250)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('imposto_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='main.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoParametro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='main.orcamento')),
            ],
        ),
    ]
