# Generated by Django 5.2.4 on 2025-08-10 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orcamento_orcamentohistorico_orcamentoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp_produtos',
            name='is_composto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProdutoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('produto_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_em', to='main.mp_produtos')),
                ('produto_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='main.mp_produtos')),
            ],
            options={
                'unique_together': {('produto_principal', 'produto_componente')},
            },
        ),
    ]
