# Generated by Django 5.2.4 on 2025-08-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mp_produtos_is_composto_produtocomponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('unidade_final', models.CharField(default='M²', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoParametrizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=250)),
                ('parametros', models.JSONField()),
                ('custo_total_centavos', models.BigIntegerField()),
                ('detalhes_calculo', models.JSONField(blank=True, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('custo_por_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produtotemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('decimal', 'Número Decimal'), ('inteiro', 'Número Inteiro'), ('selecao', 'Seleção (Lista)'), ('produto', 'Produto/Material')], max_length=10)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('valor_padrao', models.CharField(blank=True, max_length=100, null=True)),
                ('opcoes_selecao', models.TextField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ajuda', models.CharField(blank=True, max_length=300, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='main.produtotemplate')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_componente', models.CharField(max_length=150)),
                ('formula_quantidade', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mp_produtos')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='main.produtotemplate')),
            ],
            options={
                'ordering': ['ordem', 'nome_componente'],
            },
        ),
    ]
