# Generated by Django 5.2.4 on 2025-08-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_produtotemplate_produtoparametrizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('aliquota', models.DecimalField(decimal_places=2, help_text='% sobre o valor', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
