# Generated by Django 5.2.4 on 2025-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_imposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp_produtos',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ex: Resinas, Fibras, Cargas Minerais', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mp_produtos',
            name='subcategoria',
            field=models.CharField(blank=True, help_text='Ex: Poliéster, Isoftálica, Epóxi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mp_produtos',
            name='tipo_produto',
            field=models.CharField(choices=[('simples', 'Produto Simples (Matéria-Prima Básica)'), ('composto', 'Produto Composto'), ('parametrizado', 'Produto Parametrizado (Template)')], default='simples', help_text='Tipo do produto na hierarquia', max_length=15),
        ),
        migrations.AlterField(
            model_name='mp_produtos',
            name='is_composto',
            field=models.BooleanField(default=False, help_text='Calculado automaticamente baseado no tipo'),
        ),
    ]
