# Generated by Django 5.2.5 on 2025-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_adicionar_hierarquia_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da mão de obra')),
                ('valor_centavos', models.BigIntegerField(help_text='Valor em centavos para maior precisão')),
                ('unidade', models.CharField(default='HORA', help_text='Unidade de cobrança (HORA, DIA, M², etc.)', max_length=20)),
                ('categoria', models.CharField(blank=True, help_text='Ex: Pultrusão, Processamento/Montagem, Operações', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mão de Obra',
                'verbose_name_plural': 'Mão de Obra',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
