# Generated by Django 5.2.5 on 2025-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_maoobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de comissão (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_inox',
            field=models.CharField(choices=[('AISI_304', 'AISI 304'), ('AISI_316', 'AISI 316'), ('AISI_316L', 'AISI 316L'), ('OUTROS', 'OUTROS')], default='AISI_304', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_resina',
            field=models.CharField(choices=[('POLIESTER', 'POLIÉSTER'), ('ISOFTALICA', 'ISOFTÁLICA'), ('EPOXI', 'EPÓXI'), ('VINILÉSTER', 'VINILÉSTER')], default='POLIESTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente_contrib_icms',
            field=models.CharField(choices=[('CONTRIBUINTE', 'CONTRIBUINTE'), ('NAO_CONTRIBUINTE', 'NÃO CONTRIBUINTE')], default='CONTRIBUINTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cnpj_faturamento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='contato',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='frete',
            field=models.CharField(choices=[('CIF', 'CIF - ENTREGA NAS DEPENDÊNCIAS DO CLIENTE'), ('FOB', 'FOB')], default='CIF', max_length=50),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='icms',
            field=models.DecimalField(decimal_places=2, default=7.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='instalacao',
            field=models.CharField(choices=[('NAO_INCLUSA', 'NÃO INCLUSA'), ('INCLUSA', 'INCLUSA')], default='NAO_INCLUSA', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='numero_orcamento',
            field=models.CharField(default='PADRÃO', max_length=50),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='uf',
            field=models.CharField(default='BA', max_length=2),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='venda_destinada',
            field=models.CharField(choices=[('REVENDA', 'REVENDA'), ('CONSUMO_PROPRIO', 'CONSUMO PRÓPRIO'), ('EXPORTACAO', 'EXPORTAÇÃO')], default='REVENDA', max_length=50),
        ),
    ]
