# Generated by Django 5.2.5 on 2025-09-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orcamento_comissao_orcamento_tipo_inox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrotemplate',
            name='template',
        ),
        migrations.AlterModelOptions(
            name='maoobra',
            options={'verbose_name': 'Mão de Obra', 'verbose_name_plural': 'Mão de Obra'},
        ),
        migrations.RenameField(
            model_name='orcamentohistorico',
            old_name='data_alteracao',
            new_name='data_acao',
        ),
        migrations.RemoveField(
            model_name='maoobra',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='maoobra',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='maoobra',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='orcamentohistorico',
            name='alterado_por',
        ),
        migrations.RemoveField(
            model_name='orcamentohistorico',
            name='descricao_mudanca',
        ),
        migrations.RemoveField(
            model_name='orcamentohistorico',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orcamentohistorico',
            name='versao',
        ),
        migrations.RemoveField(
            model_name='orcamentoitem',
            name='imposto_item',
        ),
        migrations.RemoveField(
            model_name='produtoparametrizado',
            name='area_total',
        ),
        migrations.RemoveField(
            model_name='produtoparametrizado',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produtoparametrizado',
            name='custo_por_unidade',
        ),
        migrations.RemoveField(
            model_name='produtoparametrizado',
            name='custo_total_centavos',
        ),
        migrations.RemoveField(
            model_name='produtoparametrizado',
            name='detalhes_calculo',
        ),
        migrations.RemoveField(
            model_name='produtoparametrizado',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='produtotemplate',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produtotemplate',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='produtotemplate',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produtotemplate',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produtotemplate',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produtotemplate',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produtotemplate',
            name='unidade_final',
        ),
        migrations.AddField(
            model_name='orcamentohistorico',
            name='acao',
            field=models.CharField(default='Criado', max_length=50),
        ),
        migrations.AddField(
            model_name='orcamentohistorico',
            name='detalhes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orcamentohistorico',
            name='usuario',
            field=models.CharField(blank=True, default='Sistema', max_length=100),
        ),
        migrations.AddField(
            model_name='orcamentoparametro',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='produtoparametrizado',
            name='custo_calculado',
            field=models.BigIntegerField(default=0, help_text='Custo calculado em centavos'),
        ),
        migrations.AddField(
            model_name='produtoparametrizado',
            name='data_calculo',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produtoparametrizado',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produtotemplate',
            name='formula_principal',
            field=models.TextField(blank=True, help_text='Fórmula principal de cálculo'),
        ),
        migrations.AddField(
            model_name='produtotemplate',
            name='parametros_obrigatorios',
            field=models.JSONField(default=list, help_text='Lista de parâmetros obrigatórios'),
        ),
        migrations.AddField(
            model_name='produtotemplate',
            name='parametros_opcionais',
            field=models.JSONField(default=dict, help_text='Parâmetros opcionais com valores padrão'),
        ),
        migrations.AddField(
            model_name='produtotemplate',
            name='produto_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='main.mp_produtos'),
        ),
        migrations.AlterField(
            model_name='maoobra',
            name='unidade',
            field=models.CharField(default='H', help_text='Unidade de medida (H=Hora, D=Dia, etc)', max_length=10),
        ),
        migrations.AlterField(
            model_name='mp_produtos',
            name='custo_centavos',
            field=models.BigIntegerField(default=0, help_text='Custo em centavos para precisão'),
        ),
        migrations.AlterField(
            model_name='mp_produtos',
            name='peso_und',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Peso por unidade em kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mp_produtos',
            name='tipo_produto',
            field=models.CharField(choices=[('simples', 'Matéria-Prima Simples'), ('composto', 'Produto Composto'), ('parametrizado', 'Template Parametrizado')], default='simples', help_text='Tipo do produto na hierarquia', max_length=15),
        ),
        migrations.AlterField(
            model_name='mp_produtos',
            name='unidade',
            field=models.CharField(default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tipo_resina',
            field=models.CharField(choices=[('POLIESTER', 'POLIÉSTER'), ('ISOFTALICA', 'ISOFTÁLICA'), ('EPOXI', 'EPÓXI'), ('VINILESTER', 'VINILÉSTER')], default='POLIESTER', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='BA', max_length=2),
        ),
        migrations.AlterField(
            model_name='orcamentoparametro',
            name='chave',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orcamentoparametro',
            name='valor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produtoparametrizado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produtoparametrizado',
            name='parametros',
            field=models.JSONField(help_text='Valores específicos dos parâmetros'),
        ),
        migrations.AlterField(
            model_name='produtoparametrizado',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='main.produtotemplate'),
        ),
        migrations.AlterField(
            model_name='produtotemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ParametroFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parametro', models.CharField(max_length=50)),
                ('formula', models.TextField(help_text='Fórmula matemática para calcular o valor')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='main.produtotemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='ComponenteTemplate',
        ),
        migrations.DeleteModel(
            name='ParametroTemplate',
        ),
    ]
