# Generated by Django 5.2.5 on 2025-09-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_parametrotemplate_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='imposto_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
