# Generated by Django 5.2.5 on 2025-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orcamentoitem_imposto_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitem',
            name='tipo_item',
            field=models.CharField(choices=[('Produto', 'Produto'), ('Serviço', 'Serviço'), ('Parametrizado', 'Produto Parametrizado')], max_length=20),
        ),
    ]
