# Generated by Django 5.2.4 on 2025-10-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_orcamentoitem_tipo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='venda_destinada',
            field=models.CharField(choices=[('INDUSTRIALIZACAO', 'INDUSTRIALIZAÇÃO'), ('USO_CONSUMO', 'USO/CONSUMO'), ('REVENDA', 'REVENDA'), ('CONSUMO_PROPRIO', 'CONSUMO PRÓPRIO'), ('EXPORTACAO', 'EXPORTAÇÃO')], default='REVENDA', max_length=50),
        ),
    ]
