# Generated by Django 5.2.4 on 2025-10-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_orcamento_venda_destinada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='venda_destinada',
            field=models.CharField(choices=[('INDUSTRIALIZACAO', 'INDUSTRIALIZAÇÃO'), ('USO_CONSUMO', 'USO/CONSUMO')], default='INDUSTRIALIZACAO', max_length=50),
        ),
    ]
