# Generated by Django 5.2.5 on 2025-10-24 14:19

from django.db import migrations


def atualizar_tipos_resina(apps, schema_editor):
    """Atualizar valores antigos de tipo_resina para os novos valores"""
    Orcamento = apps.get_model('main', 'Orcamento')
    
    # Mapear valores antigos para novos
    mapeamento = {
        'EPOXI': 'POLIESTER',  # Converter EPOXI para POLIESTER (mais comum)
        'VINILESTER': 'ESTER_VINILICA',  # Converter VINILESTER para ESTER_VINILICA
    }
    
    for valor_antigo, valor_novo in mapeamento.items():
        Orcamento.objects.filter(tipo_resina=valor_antigo).update(tipo_resina=valor_novo)
        print(f"Atualizados registros de {valor_antigo} para {valor_novo}")


def reverter_tipos_resina(apps, schema_editor):
    """Reverter as mudanças se necessário"""
    Orcamento = apps.get_model('main', 'Orcamento')
    
    # Mapear de volta
    mapeamento = {
        'ESTER_VINILICA': 'VINILESTER',
    }
    
    for valor_novo, valor_antigo in mapeamento.items():
        Orcamento.objects.filter(tipo_resina=valor_novo).update(tipo_resina=valor_antigo)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_orcamento_venda_destinada'),
    ]

    operations = [
        migrations.RunPython(atualizar_tipos_resina, reverter_tipos_resina),
    ]
