# Generated by Django 5.2.5 on 2025-10-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_atualizar_tipos_resina'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='ipi_item',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de IPI', max_digits=5),
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='unidade',
            field=models.CharField(default='UN', help_text='Unidade de medida', max_length=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tipo_resina',
            field=models.CharField(choices=[('POLIESTER', 'POLIÉSTER'), ('ISOFTALICA', 'ISOFTÁLICA'), ('ESTER_VINILICA', 'ÉSTER VINÍLICA')], default='POLIESTER', max_length=20),
        ),
    ]
