# Generated by Django 5.2.5 on 2025-10-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orcamentoitem_ipi_item_orcamentoitem_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp_produtos',
            name='descricao_tecnica',
            field=models.TextField(blank=True, help_text='Descrição técnica detalhada do produto', null=True),
        ),
        migrations.AddField(
            model_name='produtotemplate',
            name='descricao_tecnica',
            field=models.TextField(blank=True, help_text='Descrição técnica detalhada do produto'),
        ),
    ]
