# Generated by Django 5.2.5 on 2025-10-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_mp_produtos_descricao_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_itens', to='main.mp_produtos'),
        ),
    ]
